# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
arch:
  - amd64
  - arm64-fraviton2
virt: lxd
group: edge
julia:
  - 1.0
  - 1.3
  - nightly
matrix:
  allow_failures:
    - julia: nightly
notifications:
  email: false
git:
  depth: 999999
# script:
#  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
#  - julia -e 'Pkg.clone(pwd()); Pkg.build("Deconvolution"); Pkg.test("Deconvolution"; coverage=true)'
after_success:
 - julia -e 'import Pkg; cd(Pkg.dir("Deconvolution")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder()); Codecov.submit(process_folder())'

jobs:
  include:
    - stage: "Documentation"
      julia: 1.3
      os: linux
      script:
        - julia --project=doc/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));
                                               Pkg.instantiate()'
        - julia --project=doc/ doc/make.jl
      after_success: skip
